### ISSUE TITLE
RealCallSpec.stream ignores error type.

### ISSUE THREAD

**Issue by aballano** [xing/xing-android-sdk#127]
The `stream()` method lifts the `rawStream()` one with `OperatorMapResponseToBodyOrError<RT, ET>` but this operator is currently ignoring the error type ET in case of an error:

```
                @Override
                public void onNext(Response<RT, ET> response) {
                    if (response.isSuccessful()) {
                        child.onNext(response.body());
                    } else {
                        child.onError(new HttpException(response));
                    }
                }

                @Override
                public void onCompleted() {
                    child.onCompleted();
                }

                @Override
                public void onError(Throwable th) {
                    child.onError(th);
                }
```

Therefore the problem is that whenever the backend returns any kind of error onNext won't be called but so will onError with a throwable like `java.io.IOException: 401 Unauthorized` thus ignoring our error type and even the JSON with the [proper reason](https://dev.xing.com/docs/error_responses).

Please correct me if I'm wrong. I'll investigate and try to make a PR tomorrow.

**Comment by aballano** [comment]
Checked, this is only happening for 401 errors.

**Comment by serj-lotutovici** [comment]
@Shyish yes, this is by design
