### ISSUE TITLE
IllegalArgumentException when using callbackUrl in XingOAuth.Builder

### ISSUE THREAD

**Issue by mig35** [xing/xing-android-sdk#140]
When we use callbackUrl it fails to validate because of:
Shared.validate should call input.matches(pattern) but not in other direction. see: https://developer.android.com/reference/java/lang/String.html#matches(java.lang.String)

Please add "." to XingOAuth.Builder.CALLBACK_PATTERN. Because we want to use "https://our.domain.com" and it will not allow us with current pattern.

iOS part works fine with this callback.

**Comment by serj-lotutovici** [comment]
Thank you for the feedback. That part is still a little bit shady (no test there). Will fix this soon.

Btw, if you have any other feedback regarding the api, feel free to open a new issue.

**Comment by mig35** [comment]
Thanks, serj-lotutovici!

**Comment by YuliaGurina** [comment]
Hi, serj-lotutovici!
I found the same problem so when the fix is expected?

**Comment by serj-lotutovici** [comment]
> I found the same problem so when the fix is expected?

@YuliaGurina this evening (my time zone is CET). Sorry currently loaded with lots of work.

**Comment by YuliaGurina** [comment]
Great, thanks a lot :)

**Comment by mig35** [comment]
@serj-lotutovici when there will be a version update, so we can use this fix? we really would like to use it. generally this is the only thing that we are waiting for our release now.

**Comment by dhartwich1991** [comment]
@mig35 Good Morning :) You could use the Snapshot Version for now (2.0.0-SNAPSHOT) and during the day I think we could release alpha version 5, i'll talk to @serj-lotutovici once he is in the office, okay?

**Comment by mig35** [comment]
Hi @dhartwich1991.
This would be great! Thanks a lot.

**Comment by dhartwich1991** [comment]
Sure no problem :) Just use the Snapshot if you really need it right now :D I promise we'll release alpha-5 in the morning (around 9:30 CEST)

**Comment by serj-lotutovici** [comment]
@mig35 can you confirm that the latest snapshot fixes your bug? If yes, I will push an alpha release

**Comment by mig35** [comment]
@serj-lotutovici, @dhartwich1991 SNAPSHOT is ok. Lets create a new alpha release! :)
Thanks!

**Comment by serj-lotutovici** [comment]
@mig35 I've published an alpha, will take a few hours till it reaches all repositories...
