### ISSUE TITLE
Drop XingOAuthCallback?

### ISSUE THREAD

**Issue by serj-lotutovici** [xing/xing-android-sdk#142]
Currently the api for `com.xing.api.oauth.XingOAuth` is a little bit misleading. The `XingOAuthCallback` implies the the response will be processed asynchronously, when in reality it's just notifying the callback based on bundle coming from the authentication activity. 

An alternative solution would be to make `XingOAuth#onActivityResult` return a `XingOAuthResponse` object, similar to `com.xing.api.Response`.

**Comment by serj-lotutovici** [comment]
cc @dhartwich1991

**Comment by ricamgar** [comment]
I like the idea of returning a `Response` instead of forcing the user to pass a listener around.
👍
