### ISSUE TITLE
Release 2.0.0 preparation

### ISSUE THREAD

**Issue by serj-lotutovici** [xing/xing-android-sdk#150]
#27.09.2016
- [x] Add CHANGELOG.md
- [x] Javadocs for all public apis
- [x] Final cleanup
- [x] Rename `LegalInformation` to `LegalInformationPreview`

**Comment by MyDogTom** [comment]
`LegalInformation` class is used inside `XingUser`. I suggest to rename it to `LegalInformationPreview` because it represents only preview of legal information.

**Comment by serj-lotutovici** [comment]
Updated the check list.
