### ISSUE TITLE
when setting xing callback uri it throws invalidarguementexception

### ISSUE THREAD

**Issue by hi0001234d** [xing/xing-android-sdk#165]
Please see the attached image, i had been completely respecting XING url format as xing had mentioned in expected input as highlighted in red circle while the actual url highlighted in green circle.
![img_07092016_163336](https://cloud.githubusercontent.com/assets/4113777/18311198/a2edd8c8-7520-11e6-9cf1-33b5a0b5cbd6.png)

Can anyone please help resolve this error because i assume now XING sdk should not through illegal argument exception but still it does.

Thanks

**Comment by serj-lotutovici** [comment]
Uf... that's a bad one... are you using the latest beta?

**Comment by serj-lotutovici** [comment]
According to https://github.com/xing/xing-android-sdk/blob/master/api-client-android-oauth/src/test/java/com/xing/api/oauth/XingOAuthTest.java#L123 this should be resolved. Also used your callback url in a local test and it passed.

Please use the latest 2.0.0-beta1 it has this issue resolved.

**Comment by hi0001234d** [comment]
Okay thank you for your reply and help, i will soon get back to you once i update to latest beta.

Thanks again

**Comment by hi0001234d** [comment]
we have now used 2.0.0-beta1 version of SDK but instead of going on to OnSuccess() method its goes to the OnError() function. below I am printing both function for your reference.help me to resolve this problem.

Both function : 

@Override
    public void onSuccess(String token, String tokenSecret)
    {
        if( is_use_legacy_pages  )
        {
            showToast("ok");
        }
        is_onSuccess = false;

```
    Prefs.getInstance(this).setOauthToken(token);
    Prefs.getInstance(this).setOauthSecret(tokenSecret);

    //appsflyer SDK code..
    if (config.isFlyerSDKUse) {
        Map<String, Object> eventValue = new HashMap<String, Object>();
        eventValue.put(AFInAppEventParameterName.LEVEL, 9);
        eventValue.put(AFInAppEventParameterName.SCORE, 100);
        AppsFlyerLib.getInstance().trackEvent( this,config.appsFlyerEventLoginWithXing, eventValue);
    }

    startActivity(new Intent(this, ProfileActivity.class).setFlags(
          Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP));
    finish();
}

@Override
public void onError() {
    showToast("error");

    is_onError = false;
}
```
