### ISSUE TITLE
XingOAuthCallback

### ISSUE THREAD

**Issue by bstobbe** [xing/xing-android-sdk#172]
Hi,

why are you removing the XingOAuthCallback and replace it with calling onActivityResult() in the calling activity? Using the XingOAuthCallback makes it easier to separate the Xing calls from the normal logic, especially if the Xing login can be done on every activity of a project

**Comment by serj-lotutovici** [comment]
Hey @bstobbe! First of all thank you for your feedback. The problem with `XingOAuthCallback` is that it misleads developers to an assumption, that the call to `onActivityResult()` is not needed, when in reality it's the only way to get the response (the activity that displays the logic form returns the response in it's **result** `Bundle`). This also allows us to test the result logic in a more straight forward way.

For your situation, I can suggest the following:
- either create a base activity, where you implement the XING authentification logic + the response and error handling, and ensure that every activity that has a XING login inherits form it. 
- or create a handler class that is used as a delegate for the XING auth handling and use it in every activity that requires it. There you can use your own callbacks, which will give you more control. But still you will have to call [XingOAuth#onActivityResult()](https://github.com/xing/xing-android-sdk/blob/master/api-client-android-oauth/src/main/java/com/xing/api/oauth/XingOAuth.java#L86).
