### ISSUE TITLE
[Proposal] Split the library in two artefacts.

### ISSUE THREAD

**Issue by serj-lotutovici** [xing/xing-android-sdk#18]
This has a few benefits, as well as a few side-effects:
- **[+]** Separate the auth activity and classes from the core of the sdk. Because the xing app implements it's own login mechanism we carry this code as loose weight.
- **[+]** Possibility to provide the sdk as a _jar_ and not an _arr_. This is a long shot, but what if java based application would also need to use an sdk, creating 2 separate libraries just doesn't make sense (will come back  with more info on this)
- **[+]** Minimize the wait of the artefact. Currently the sdk 1.0.0 is 186.07 K, in comparision [retrofit](http://search.maven.org/#artifactdetails%7Ccom.squareup.retrofit%7Cretrofit%7C2.0.0-beta2%7Cjar) is only 67K 
- **[-/+]** If we go with the java only track we lose the possibility of accessing some of android's apis, for a library that makes network calls and handles responses this may not be an issue, but what if the sdk will become something more?
- **[-]** The sdk will have to be semi aware of the environment its running on, which means extra support for both platforms (java and android). We will also have to keep in mind that android is still in the **java 7(6?)** world and this restricts us from blindly moving to a newer java version, or even using some java 7 apis like _try-with-resources_ (seriously Google couldn't back port that >_>) 
- **[-]** The module classes will may have to become just module classes with no awareness of some android interfaces (again adding to the plain java track)

For now it's just an idea an crazy mans head.

**Comment by dhartwich1991** [comment]
Partially working on this

**Comment by serj-lotutovici** [comment]
#33 did this partially... we also need to consider dropping the `Parcelable` interface. The performance improvement is pretty low at this point.

**Comment by serj-lotutovici** [comment]
Yet another proposal. Third parties require permissions to be able to access each resource. Most of the time a permission for one resource implies an additional privacy permission form the user. Some clients don't consume most of the apis, and may not require all resources + the data models. May be it makes sense to do yet another split, and introduce resource modularity.
@dhartwich1991 @andretietz what do you guys think?

**Comment by serj-lotutovici** [comment]
Closing this issue, since there is nothing more we can do here. Will open another one for the resource split.
