### ISSUE TITLE
[Architecture] Drop singletons

### ISSUE THREAD

**Issue by serj-lotutovici** [xing/xing-android-sdk#23]
Since the current implementation is causing crashes doe to activity and application lifecycle, we need to avoid implementing the singleton pattern for the user. The design should promote the users to create a single object of the `XingController` via a simple builder and use it, instead of relying on us to do that.

This means:
- No need for initialisation checks during instance access (this should be done only once by the builder during creation of the `XingController`). Short: If the instance was created by the builder, it is a valid one, loss of the instance will require to recreate it.
- No need for the `XingController#flush()`, if the user whats to drop or re-initialise the object, he will only  have to `null` the reference.
- Allows users to inject the instance via  a Dependency Injection framework, instead of loosing control of where the `XingController#getInstance()` is called.

**Comment by serj-lotutovici** [comment]
@dhartwich1991 I thing it's time to delete the `XingController` and other shit that it brought upon us...

**Comment by dhartwich1991** [comment]
:tada: :beers:
