### ISSUE TITLE
OAuth credentials

### ISSUE THREAD

**Issue by asmaps** [xing/xing-android-sdk#230]
Hi,

I tried to play around with the API client, but I can't find my OAuth-Credentials. When I go to the page described in the README under "2. Add OAuth credentials to your project" I can't create an app to retrieve my credentials. Where do I have to click? It says "You don’t have any apps, ask your XING representative if you need to create one.", but there is no contact address or whatever. How can I get the client to work?

Regards

**Comment by asmaps** [comment]
Oh... I just saw the first big line in the README. That's sad :-( So it's not possible at all to get an API key?

**Comment by MyDogTom** [comment]
>So it's not possible at all to get an API key?

Sorry, but it's not possible anymore.
