### ISSUE TITLE
[api-client] Handle Content-Range

### ISSUE THREAD

**Issue by serj-lotutovici** [xing/xing-android-sdk#98]
For some requests with pagination, XWS returns a `Content-Range` header which contains the current data offset + total values.
If the header is set, there are to possible outcomes:
- `Content-Range: items 2-23/130` (if the **total** is known)
- `Content-Range: items 3-34/*` (if the **total** is unknown)

We need to parse this on a successful response, and pass this data inside a field of `com.xing.api.Resposne`.

**Comment by serj-lotutovici** [comment]
@Shyish @dhartwich1991 I'm thinking of something like: `Response#range()` where range is:

```
class ContentRange {
  int total;
  int currentOffset;
  int currentLast;
}
```

what do you guys think?

**Comment by serj-lotutovici** [comment]
Since this is not supported by xws... we can hack for now, by pre-parsing the total value form requests that contain it...

**Comment by aballano** [comment]
:+1:
